# Generated by Django 4.1.7 on 2023-02-27 16:13

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectID", models.CharField(max_length=200)),
                ("dataFileID", models.CharField(max_length=200)),
                (
                    "addTime",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 27, 16, 13, 48, 423309)
                    ),
                ),
                ("image", models.FileField(upload_to="MedImgAI/SaveImage_temp/")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectID", models.CharField(max_length=200)),
                ("teamName", models.CharField(max_length=200)),
                ("isPublic", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=500)),
                (
                    "createdTime",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 27, 16, 13, 48, 425831)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectID", models.CharField(max_length=200)),
                ("dataFileID", models.CharField(max_length=200)),
                (
                    "brainInputImage",
                    models.FileField(upload_to="MedImgAI/SaveImage_temp/"),
                ),
                (
                    "labelOutputImage",
                    models.FileField(upload_to="MedImgAI/SaveImage_temp/"),
                ),
                (
                    "previewImage",
                    models.FileField(upload_to="MedImgAI/SaveImage_temp/"),
                ),
                (
                    "labelOutput3DImage",
                    models.FileField(upload_to="MedImgAI/SaveImage_temp/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamName", models.CharField(max_length=200)),
                ("owner", models.CharField(max_length=200)),
                ("scale", models.CharField(max_length=200)),
                ("isPublic", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=500)),
                (
                    "createdTime",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 27, 16, 13, 48, 424305)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamName", models.CharField(max_length=200)),
                ("userName", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=200)),
                (
                    "createdTime",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 27, 16, 13, 48, 425307)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("password", models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Usertoken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("token", models.CharField(max_length=200)),
            ],
        ),
    ]
