# Generated by Django 4.1.7 on 2023-03-04 23:55

import MedImgAI.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedImgAI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ifProcessed',
            field=models.CharField(default='No', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='teamName',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 23, 55, 28, 235047)),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=MedImgAI.models.upload_to),
        ),
        migrations.AlterField(
            model_name='project',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 23, 55, 28, 237046)),
        ),
        migrations.AlterField(
            model_name='team',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 23, 55, 28, 236047)),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 23, 55, 28, 237046)),
        ),
    ]
