# Generated by Django 4.1.7 on 2023-03-05 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedImgAI', '0002_image_ifprocessed_image_teamname_alter_image_addtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='ifProcessed',
        ),
        migrations.RemoveField(
            model_name='image',
            name='teamName',
        ),
        migrations.AlterField(
            model_name='image',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 0, 7, 37, 978733)),
        ),
        migrations.AlterField(
            model_name='project',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 0, 7, 37, 980733)),
        ),
        migrations.AlterField(
            model_name='team',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 0, 7, 37, 979732)),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 0, 7, 37, 980733)),
        ),
    ]
