# Generated by Django 4.1.7 on 2023-03-05 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedImgAI', '0003_remove_image_ifprocessed_remove_image_teamname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=200)),
                ('projectID', models.CharField(max_length=200)),
                ('dataFileID', models.CharField(max_length=200)),
                ('ifProcessed', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 0, 30, 38, 204886)),
        ),
        migrations.AlterField(
            model_name='project',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 0, 30, 38, 208888)),
        ),
        migrations.AlterField(
            model_name='team',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 0, 30, 38, 206890)),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 0, 30, 38, 207889)),
        ),
    ]
