# Generated by Django 4.1.7 on 2023-03-05 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedImgAI', '0004_database_alter_image_addtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 15, 19, 22, 430946)),
        ),
        migrations.AlterField(
            model_name='project',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 15, 19, 22, 430946)),
        ),
        migrations.AlterField(
            model_name='team',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 15, 19, 22, 430946)),
        ),
        migrations.AlterField(
            model_name='team',
            name='scale',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 15, 19, 22, 430946)),
        ),
    ]
