# Generated by Django 4.1.7 on 2023-03-05 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedImgAI', '0005_alter_image_addtime_alter_project_createdtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.CharField(max_length=200)),
                ('alpha', models.FloatField(max_length=200)),
                ('epoch', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 18, 50, 19, 69709)),
        ),
        migrations.AlterField(
            model_name='project',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 18, 50, 19, 72711)),
        ),
        migrations.AlterField(
            model_name='team',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 18, 50, 19, 71711)),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 18, 50, 19, 71711)),
        ),
    ]
